/left_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_outer_knuckle_joint
  gains:
    left_outer_knuckle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
barrett:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - bh_j11_joint
    - bh_j12_joint
    - bh_j22_joint
    - bh_j32_joint
  gains:
    bh_j11_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bh_j12_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bh_j22_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bh_j32_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1