controller_list:
  - name: /left_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_outer_knuckle_joint
      - left_inner_knuckle_joint
      - left_finger_joint